--
-- Script was generated by Devart dbForge Studio for MySQL, Version 8.0.40.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 7/9/2018 11:42:43
-- Server version: 5.5.5-10.1.34-MariaDB
-- Client version: 4.1
--


SET NAMES 'utf8';

--
-- Inserting data into table universidad.carrera
--
INSERT INTO universidad.carrera(cod_Carrera, Nombre) VALUES
(10000, 'INGENIERIA INDUSTRIAL'),
(10001, 'INGENIERIA DE SISTEMAS'),
(10002, 'INGENIERIA PETROLERA'),
(10003, 'INGENIERIA FINANCIERA'),
(10004, 'INGENIERIA COMERCIAL'),
(10005, 'MARKETING'),
(10006, 'COMUNICACIÓN'),
(10007, 'ECONOMIA'),
(10008, 'DISEÑO GRAFICO'),
(10009, 'DERECHO'),
(10010, 'INGENIERIA ELECTRICA'),
(1005, 'INGENIERIA CIVIL');