--
-- Script was generated by Devart dbForge Studio for MySQL, Version 8.0.40.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 7/9/2018 13:48:22
-- Server version: 5.5.5-10.1.34-MariaDB
-- Client version: 4.1
--


SET NAMES 'utf8';

--
-- Inserting data into table universidad.aula
--
INSERT INTO universidad.aula(cod_Aula, cod_Edificio, Nombre, Piso) VALUES
(30001, 31001, 'AULA -2', 2),
(30002, 31002, 'AULA -3', 3),
(30003, 31003, 'AULA -4', 1),
(30004, 31000, 'AULA -5', 2),
(30005, 31001, 'AULA -6', 3),
(30006, 31002, 'AULA -7', 1),
(30007, 31003, 'AULA -8', 2),
(30008, 31000, 'AULA -9', 3),
(30009, 31001, 'AULA -10', 1),
(30010, 31002, 'AULA -11', 2),
(30011, 31003, 'AULA -12', 3),
(30012, 31000, 'AULA -13', 1),
(30013, 31001, 'AULA -14', 2),
(30014, 31002, 'AULA -15', 3),
(30015, 31003, 'AULA -16', 1),
(30016, 31000, 'AULA -17', 2),
(30017, 31001, 'AULA -18', 3),
(30018, 31002, 'AULA -19', 1),
(30019, 31003, 'AULA -20', 2),
(30020, 31000, 'AULA -21', 3),
(30021, 31001, 'AULA -22', 1),
(30022, 31002, 'AULA -23', 2),
(30023, 31003, 'AULA -24', 3),
(30024, 31000, 'AULA -25', 1),
(30025, 31001, 'AULA -26', 2),
(30026, 31002, 'AULA -27', 3),
(30027, 31003, 'AULA -28', 1),
(30028, 31005, 'AULA -29', 2)