--
-- Script was generated by Devart dbForge Studio for MySQL, Version 8.0.40.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 7/9/2018 11:28:38
-- Server version: 5.5.5-10.1.34-MariaDB
-- Client version: 4.1
--


SET NAMES 'utf8';

BEGIN;

--
-- Inserting data into table universidad.estudiante
--
INSERT INTO universidad.estudiante(cod_Estudiante, cod_Carrera, Nombre, Dirección, Correoelectrónico) VALUES
(601, 10005, 'AGRAMONT CARRILLO YURISA ANDREA', 'OBRAJES AV. HERNANDO SILES # 5411 CALLE 8', 'gabriel.escobar.091@gmail.com');
INSERT INTO universidad.estudiante(cod_Estudiante, cod_Carrera, Nombre, Dirección, Correoelectrónico) VALUES
(602, 10005, 'AGREDA RUIZ CAMILA', 'C/CANADA Y HOLANDA (ZONA VALLE HERMOSO)', 'escobar20@hotmail.es');
INSERT INTO universidad.estudiante(cod_Estudiante, cod_Carrera, Nombre, Dirección, Correoelectrónico) VALUES
(603, 10005, 'AGUDO GUERRA DANIELA', 'C. PULACAYO #482', 'martinescobar777_@hotmail.com');
INSERT INTO universidad.estudiante(cod_Estudiante, cod_Carrera, Nombre, Dirección, Correoelectrónico) VALUES
(604, 10005, 'AGUILAR JALDIN LUIS ESTEBAN', 'BARRIO MANACO - QUILLACOLLO', NULL);
INSERT INTO universidad.estudiante(cod_Estudiante, cod_Carrera, Nombre, Dirección, Correoelectrónico) VALUES
(605, 10005, 'AGUILAR LEDES CAROLINA', 'URB. VALLE DEARANJUEZ C. LA VIZCACHA # D-5', 'despinoza3@upb.edu');
INSERT INTO universidad.estudiante(cod_Estudiante, cod_Carrera, Nombre, Dirección, Correoelectrónico) VALUES
(606, 10005, 'AGUILAR ROCHA KAREN', 'AV. BUSCH ESQ. HONDURAS Nº 885', 'alexandraespinoza1306@gmail.com');
INSERT INTO universidad.estudiante(cod_Estudiante, cod_Carrera, Nombre, Dirección, Correoelectrónico) VALUES
(607, 10005, 'AGUILAR ZURITA BRANDON', 'C. COLOMBIA S/N', 'iguiexbad@hotmail.com');
INSERT INTO universidad.estudiante(cod_Estudiante, cod_Carrera, Nombre, Dirección, Correoelectrónico) VALUES
(608, 10005, 'AGUIRRE BALDERRAMA SEBASTIAN ALEJANDRO', 'CALACOTO CALLE 22 NO. EDIF. MONTE CRISTO DEPTO 9A', 'yesmenia.et1996@gmail.com');
INSERT INTO universidad.estudiante(cod_Estudiante, cod_Carrera, Nombre, Dirección, Correoelectrónico) VALUES
(609, 10005, 'AGUIRRE GOITIA GISELLE  ADRIANA', 'CALLE DIEGO DE PERALTA N° 944 MIRAFLORES', 'jessicaviscarra@hotmail.com');
INSERT INTO universidad.estudiante(cod_Estudiante, cod_Carrera, Nombre, Dirección, Correoelectrónico) VALUES
(610, 10005, 'AGUIRRE RODRIGUEZ MIGUEL FABRICIO', 'AV. CAP USTARIZ KM. 6.5, BARRIO SANTA ROSA', 'emyfaccio@gmail.com');
INSERT INTO universidad.estudiante(cod_Estudiante, cod_Carrera, Nombre, Dirección, Correoelectrónico) VALUES
(611, 10005, 'AIZAMA ARIAS CARLA FABIANA', 'J. AGUIRRE ACHA', 'bfedic@upb.edu');
INSERT INTO universidad.estudiante(cod_Estudiante, cod_Carrera, Nombre, Dirección, Correoelectrónico) VALUES
(612, 10005, 'AIZAMA ARIAS JORGE CHRISTIAN', 'V. FATIMA PLAZA DEL MAESTRO', 'pfernandez@upb.edu');
INSERT INTO universidad.estudiante(cod_Estudiante, cod_Carrera, Nombre, Dirección, Correoelectrónico) VALUES
(613, 10005, 'ALBA GUTIERREZ DIANA KATHERINE', 'SIDUMSS NORTE', 'jhoni_jh@hotmail.com');
INSERT INTO universidad.estudiante(cod_Estudiante, cod_Carrera, Nombre, Dirección, Correoelectrónico) VALUES
(614, 10005, 'ALBA MARTINEZ ALEJANDRO VALENTIN', 'CALLE 15 CALACOTO ESQ. COSTANERA', 'kike.mafer@gmail.com');
INSERT INTO universidad.estudiante(cod_Estudiante, cod_Carrera, Nombre, Dirección, Correoelectrónico) VALUES
(615, 10005, 'ALBA MIRANDA JORGE GUILLERMO', 'ACUMANI CALLE 21 #51', 'vanessa-hp-hotmail.com');
INSERT INTO universidad.estudiante(cod_Estudiante, cod_Carrera, Nombre, Dirección, Correoelectrónico) VALUES
(616, 10005, 'ALBA MIRANDA OSCAR ALEJANDRO', '', 'jfernandez@lp.upb.edu');
INSERT INTO universidad.estudiante(cod_Estudiante, cod_Carrera, Nombre, Dirección, Correoelectrónico) VALUES
(617, 10006, 'ALBARRACIN SILVA RAYZA TATIANA', 'AV.JUAN PABLO II Y AV.DORBIGNI', 'kalu.13.kf@gmail.com');
INSERT INTO universidad.estudiante(cod_Estudiante, cod_Carrera, Nombre, Dirección, Correoelectrónico) VALUES
(618, 10006, 'ALBIS APAZA JUAN CARLOS', 'NUEVA GRANADA 1618', 'notiene@notiene.com');
INSERT INTO universidad.estudiante(cod_Estudiante, cod_Carrera, Nombre, Dirección, Correoelectrónico) VALUES
(619, 10006, 'ALBORTA ABASTOFLOR DANIEL ANDRES', 'JULIO MENDEZ', 'jireh_sito@hotmail.com');
INSERT INTO universidad.estudiante(cod_Estudiante, cod_Carrera, Nombre, Dirección, Correoelectrónico) VALUES
(620, 10006, 'ALBORTA INARRA DANIEL ALEJANDRO', 'BARRIO FLORIDA SUR N° 78', 'walterferreyrab@gmail.com');
INSERT INTO universidad.estudiante(cod_Estudiante, cod_Carrera, Nombre, Dirección, Correoelectrónico) VALUES
(621, 10006, 'ALBORTA NADA ROMINA', 'LOS PINOS BLOQUE 142 DEP. 300', 'KATERIN_FERRUFINO@HOTMAIL.COM');
INSERT INTO universidad.estudiante(cod_Estudiante, cod_Carrera, Nombre, Dirección, Correoelectrónico) VALUES
(622, 10006, 'ALE BALDIVIESO LEXANDER', 'EDF. LAS PALMAS III DPTO. 9', 'pao.ferrufino@gmail.com');
INSERT INTO universidad.estudiante(cod_Estudiante, cod_Carrera, Nombre, Dirección, Correoelectrónico) VALUES
(623, 10006, 'ALGARAÑAZ VILLAFAN CARLOS SANTIAGO', 'LOS NUEVOS PINOS BLOQUE 13 DEPTO. 8A', 'amrafael@hotmail.es');
INSERT INTO universidad.estudiante(cod_Estudiante, cod_Carrera, Nombre, Dirección, Correoelectrónico) VALUES
(624, 10006, 'ALI CARLO LIZBETH', 'CALLE CHACO  N° 738', 'dflor@upb.edu');
INSERT INTO universidad.estudiante(cod_Estudiante, cod_Carrera, Nombre, Dirección, Correoelectrónico) VALUES
(625, 10006, 'ALIAGA GOMEZ VALERIA ISABEL', 'ALTO IRPAVI CALLE 4 NO. 11', 'afloresc@bcp.com.bo');
INSERT INTO universidad.estudiante(cod_Estudiante, cod_Carrera, Nombre, Dirección, Correoelectrónico) VALUES
(626, 10006, 'ALIAGA JIMENEZ AMEDH FELIPE', 'AV. CAMPERO # 330 ZONA LA CHIMBA', 'eflorese@bmsc.com.bo');
INSERT INTO universidad.estudiante(cod_Estudiante, cod_Carrera, Nombre, Dirección, Correoelectrónico) VALUES
(627, 10006, 'ALIPAZ WOZNIECKI DANIEL MAREK KRZYSZTOF', 'AV JAVIER DEL GRANADO C/29 NO. 490 Z', NULL);
INSERT INTO universidad.estudiante(cod_Estudiante, cod_Carrera, Nombre, Dirección, Correoelectrónico) VALUES
(628, 10006, 'ALPIRE GONZALES ANDREA LESLY', 'ACHUMANI CALLE 29 # 490', 'faflor97@gmail.com');
INSERT INTO universidad.estudiante(cod_Estudiante, cod_Carrera, Nombre, Dirección, Correoelectrónico) VALUES
(629, 10006, 'ALVAREZ MAMANI SVENN ROLANDO', 'CALLE VALDIVIESO EDIFICIO ALAMEDA DEPTO 3-C', 'RoyalDanFM@gmail.com');
INSERT INTO universidad.estudiante(cod_Estudiante, cod_Carrera, Nombre, Dirección, Correoelectrónico) VALUES
(630, 10006, 'ALVAREZ SECKO ERICK EDUARDO', 'CALLE MURGUIA Y TADEO AHENKE', 'jessygfm@gmail.com');
INSERT INTO universidad.estudiante(cod_Estudiante, cod_Carrera, Nombre, Dirección, Correoelectrónico) VALUES
(631, 10006, 'ALVIS BETANCOURT WALTER MAURICIO', 'AV. BLANCO GALINDO S/N QLLO. ENTRE C. SANTA CRUZ Y BALLIVIAN', 'pjflores@upb.edu');
INSERT INTO universidad.estudiante(cod_Estudiante, cod_Carrera, Nombre, Dirección, Correoelectrónico) VALUES
(632, 10006, 'ALVIS RODAS VANIA CAROLINA', 'PARQUE LA TORRE 815', 'holasoyyo603@hotmail.com');
INSERT INTO universidad.estudiante(cod_Estudiante, cod_Carrera, Nombre, Dirección, Correoelectrónico) VALUES
(633, 10006, 'ALZUGARAY GONZALES MICHELLE VALERIA', 'C. SAN MARTIN Y COLOMBIA', 'ofranco@upb.edu');
INSERT INTO universidad.estudiante(cod_Estudiante, cod_Carrera, Nombre, Dirección, Correoelectrónico) VALUES
(634, 10006, 'AMATLLER ORSOLINI VALERIA PAOLA', 'LA FLORIDA AV. LA RINCONADA #34', 'manukfranco@gmail.com');
INSERT INTO universidad.estudiante(cod_Estudiante, cod_Carrera, Nombre, Dirección, Correoelectrónico) VALUES
(635, 10006, 'AMPUERO TORDOYA ANA DANIELA', 'AV. UYUNI CONDOMINIO GUADALUPE DEPTO 3G', 'leyfranm@gmail.com');
INSERT INTO universidad.estudiante(cod_Estudiante, cod_Carrera, Nombre, Dirección, Correoelectrónico) VALUES
(636, 10006, 'ANDAVEREZ CARDON PEDRO FIDEL', 'LOS PINOS CALLE 35', 'doriamfe@hotmail.com');
INSERT INTO universidad.estudiante(cod_Estudiante, cod_Carrera, Nombre, Dirección, Correoelectrónico) VALUES
(637, 10006, 'ANDIA ANTEZANA DIEGO MAURICIO', 'CALLE 14 CALALCOTO NO 400', 'lfuentes@upb.edu');
INSERT INTO universidad.estudiante(cod_Estudiante, cod_Carrera, Nombre, Dirección, Correoelectrónico) VALUES
(638, 10006, 'ANDRADE MEMM FERNANDA', 'ESTEBAN ARZE # 778', 'fabriziofusco98123@gmail.com');
INSERT INTO universidad.estudiante(cod_Estudiante, cod_Carrera, Nombre, Dirección, Correoelectrónico) VALUES
(639, 10006, 'ANEYBA MELGAR ADRIÁN NICOLÁS', 'CALLE JULIO MENDEZ N° 1574', 'jhonattan_fusco_@hotmail.com');
INSERT INTO universidad.estudiante(cod_Estudiante, cod_Carrera, Nombre, Dirección, Correoelectrónico) VALUES
(640, 10006, 'ANGELERI CHAVEZ CESSARE ALESSANDRO', 'CALLE CASIMIRO CORRALES N. 1051', 'ggallo@upb.edu');
INSERT INTO universidad.estudiante(cod_Estudiante, cod_Carrera, Nombre, Dirección, Correoelectrónico) VALUES
(641, 10006, 'ANGULO LEDEZMA FLAVIA FERNANDA', 'CALLE DANIEL CAMPOS ESQ. CHACO', 'igamboa@upb.edu');
INSERT INTO universidad.estudiante(cod_Estudiante, cod_Carrera, Nombre, Dirección, Correoelectrónico) VALUES
(642, 10006, 'ANTEQUERA ROCABADO CARLA', 'C. MEXICO # 1433', 'rodrigogamboach8@gmail.com');
INSERT INTO universidad.estudiante(cod_Estudiante, cod_Carrera, Nombre, Dirección, Correoelectrónico) VALUES
(643, 10006, 'ANTEZANA ARNEZ NOELIA', 'CONDOMINIO CASTAÑAS #3', 'marcelogamboatorrez@gmail.com');
INSERT INTO universidad.estudiante(cod_Estudiante, cod_Carrera, Nombre, Dirección, Correoelectrónico) VALUES
(644, 10007, 'ANTEZANA AYALA FABIOLA', 'CALLE TRINIDAD TOBAGO NO. 1047 MIRAFLORES', 'mariel_gc16@hotmail.com');
INSERT INTO universidad.estudiante(cod_Estudiante, cod_Carrera, Nombre, Dirección, Correoelectrónico) VALUES
(645, 10007, 'ANTEZANA LOROÑA BERNARDO DANIEL', '', 'mgarcia6@upb.edu');
INSERT INTO universidad.estudiante(cod_Estudiante, cod_Carrera, Nombre, Dirección, Correoelectrónico) VALUES
(646, 10007, 'ANTEZANA TERAN MARIANO', '6 DE AGOSTO ESQUINA CLAVIJO EDIF. EL PROGRESO PISO 6 DEPTO C1', 'mauri_garcia_e@hotmail.com');
INSERT INTO universidad.estudiante(cod_Estudiante, cod_Carrera, Nombre, Dirección, Correoelectrónico) VALUES
(647, 10007, 'ANTEZANA VALDIVIA ISAAC VLADIMIR', 'MAN CESPED , WASHIBGTON EDIF. ISABELA', 'basketball-sg57@hotmail.com');
INSERT INTO universidad.estudiante(cod_Estudiante, cod_Carrera, Nombre, Dirección, Correoelectrónico) VALUES
(648, 10007, 'ANTEZANA VASQUEZ MARIEL FABIOLA', 'AV. 6 DE AGOSTO EDIF. QUINTO CENTENARIO #2006 11-B', 'norman_garcia33@hotmail.com');
INSERT INTO universidad.estudiante(cod_Estudiante, cod_Carrera, Nombre, Dirección, Correoelectrónico) VALUES
(649, 10007, 'APAZA CHALCO ELVIN ARIEL', 'CALLE CLAUDIO PADILLA NO. 1549 MIRAFLORES', 'ogarcia@upb.edu');
INSERT INTO universidad.estudiante(cod_Estudiante, cod_Carrera, Nombre, Dirección, Correoelectrónico) VALUES
(650, 10007, 'APAZA CHURQUI VANESA ESTHER', 'AV. BLANCO GALINDO KM. 7 1/2', 'lalugh2405@gmail.com');
INSERT INTO universidad.estudiante(cod_Estudiante, cod_Carrera, Nombre, Dirección, Correoelectrónico) VALUES
(651, 10007, 'APONTE GOMEZ PAUL ANDRES', 'AV. AMERICA Y SANTA CRUZ EDF. VICTORIA P3-E', 'jgarcia4@upb.edu');
INSERT INTO universidad.estudiante(cod_Estudiante, cod_Carrera, Nombre, Dirección, Correoelectrónico) VALUES
(652, 10007, 'AQUINO ARAGON SHEILA BERTHA', 'IRPAVI CALLE 2', 'dudaso96@hotmail.com');
INSERT INTO universidad.estudiante(cod_Estudiante, cod_Carrera, Nombre, Dirección, Correoelectrónico) VALUES
(653, 10007, 'ARACENA NOYA JESSICA FABIOLA', '', 'zarhimgr@gmail.com');
INSERT INTO universidad.estudiante(cod_Estudiante, cod_Carrera, Nombre, Dirección, Correoelectrónico) VALUES
(654, 10007, 'ARACENA SORIA GALVARRO  MARIA FERNANDA', 'BLANCO GALINDO KM. 7 1/2 LA FLORIDA SUD N° 44', 'nicolasgilmejia@hotmail.com');
INSERT INTO universidad.estudiante(cod_Estudiante, cod_Carrera, Nombre, Dirección, Correoelectrónico) VALUES
(655, 10007, 'ARAMAYO ARANDA RAFAEL GUILLERMO', '', 'g.gabo@hotmail.com');
INSERT INTO universidad.estudiante(cod_Estudiante, cod_Carrera, Nombre, Dirección, Correoelectrónico) VALUES
(656, 10007, 'ARANCIBIA MEDRANO ARIEL ROBERTO', 'AV. HERNEST # 4, BAJO SEGUENCOMA', NULL);
INSERT INTO universidad.estudiante(cod_Estudiante, cod_Carrera, Nombre, Dirección, Correoelectrónico) VALUES
(657, 10007, 'ARANCIBIA MEDRANO FABIAN RODRIGO', '', 'nickygc95@gmail.com');
INSERT INTO universidad.estudiante(cod_Estudiante, cod_Carrera, Nombre, Dirección, Correoelectrónico) VALUES
(658, 10007, 'ARANDA DE LA REZA JAZMIN ALEJANDRA', 'AV. ARCE ESQUINA MONTEVIDEO Nº 2081', 'rodrior@gmail.com');
INSERT INTO universidad.estudiante(cod_Estudiante, cod_Carrera, Nombre, Dirección, Correoelectrónico) VALUES
(659, 10007, 'ARANDIA ARAUCO AGUSTIN', 'C/FRANCISCO BEDREGAL # 12 (ZONA TEMPORAL)', 'marcelo.gomez.ortiz@gmail.com');
INSERT INTO universidad.estudiante(cod_Estudiante, cod_Carrera, Nombre, Dirección, Correoelectrónico) VALUES
(660, 10007, 'ARANDIA VEGA SHARON KELLY', 'C. AIRAMPO NRO. 139, ZONA TAQUIÑA', 'jennygomez170199@hotmail.com');
INSERT INTO universidad.estudiante(cod_Estudiante, cod_Carrera, Nombre, Dirección, Correoelectrónico) VALUES
(661, 10007, 'ARANDIA VELASCO YERKO HERNAN', '', 'karen_gonchi@hotmail.com');
INSERT INTO universidad.estudiante(cod_Estudiante, cod_Carrera, Nombre, Dirección, Correoelectrónico) VALUES
(662, 10007, 'ARANIBAR FERNANDEZ ALVARO ALEJANDRO', '', 'carlyga@gmail.com');
INSERT INTO universidad.estudiante(cod_Estudiante, cod_Carrera, Nombre, Dirección, Correoelectrónico) VALUES
(663, 10007, 'ARCE SOTO MARTIN MARCELO', 'CALLE ZENON SALINAS NRO. 935', 'IGNACIO GONZLESBARRON@GMAIL.COM');
INSERT INTO universidad.estudiante(cod_Estudiante, cod_Carrera, Nombre, Dirección, Correoelectrónico) VALUES
(664, 10007, 'ARCIENEGA ALCOCER ADRIANA', 'C/EMILIANO ZAPATA # 764 (ZONA QUERU QUERU)', NULL);
INSERT INTO universidad.estudiante(cod_Estudiante, cod_Carrera, Nombre, Dirección, Correoelectrónico) VALUES
(665, 10008, 'ARCIENEGA ANGLES DANIELA NICOLE', 'FRANCISCO BEDREGAL Nº542', 'jagonzalescabrera@gmail.com');
INSERT INTO universidad.estudiante(cod_Estudiante, cod_Carrera, Nombre, Dirección, Correoelectrónico) VALUES
(666, 10008, 'ARDAYA LOPEZ SERGIO EDUARDO', 'CALLE AULLAGAS N° 63 SARCO', NULL);
INSERT INTO universidad.estudiante(cod_Estudiante, cod_Carrera, Nombre, Dirección, Correoelectrónico) VALUES
(667, 10008, 'ARELLANO NAZER FRANCISCO JAVIER', 'CALACOTOC/25 URB PINOS NORTE 92', 'nessitarommy@gmail.com');
INSERT INTO universidad.estudiante(cod_Estudiante, cod_Carrera, Nombre, Dirección, Correoelectrónico) VALUES
(668, 10008, 'ARELLANO NAZER JUAN CRISTOBAL', 'CALLE 24 DE SEPTIEMBRE  N° 557 COTA COTA', NULL);
INSERT INTO universidad.estudiante(cod_Estudiante, cod_Carrera, Nombre, Dirección, Correoelectrónico) VALUES
(669, 10008, 'ARELLANO ZAMORA SEBASTIAN', 'C/JUAN JOSE DIAZ GAINZA # 233 (URB. EL PROFESIONAL)', 'ogonzales@ypfb.gob.bo');
INSERT INTO universidad.estudiante(cod_Estudiante, cod_Carrera, Nombre, Dirección, Correoelectrónico) VALUES
(670, 10008, 'ARENAS PEREIRA HORACIO', 'C/MARIANO MENDEZ # 16 (ZONA EL MIRADOR)', 'agonzales5@upb.edu');
INSERT INTO universidad.estudiante(cod_Estudiante, cod_Carrera, Nombre, Dirección, Correoelectrónico) VALUES
(671, 10008, 'ARGOTE PEREZ CAROLINA', 'ANTOFAGASTA (TIQUIPAYA)', 'PATRICKGONZALESWILSTERMANN@HOTMAIL.COM');
INSERT INTO universidad.estudiante(cod_Estudiante, cod_Carrera, Nombre, Dirección, Correoelectrónico) VALUES
(672, 10008, 'ARIAS ESCOBAR MICHELLE FERNANDA', 'CALLE CHIPAYA CONDOMINIO MEDITERRANEO II', 'ale_gowu@hotmail.com');
INSERT INTO universidad.estudiante(cod_Estudiante, cod_Carrera, Nombre, Dirección, Correoelectrónico) VALUES
(673, 10008, 'ARIAS MURILLO KEVIN FLAVIO', 'SOMBRERO DE CHOLA 3 CUADRAS ARRIBA EDIFICIO RESIDENZA', NULL);
INSERT INTO universidad.estudiante(cod_Estudiante, cod_Carrera, Nombre, Dirección, Correoelectrónico) VALUES
(674, 10008, 'ARMAZA NAVIA EDUARDO REYNALDO', 'JUAN DE LA CRUZ TORRES', 'gonzalezpozo@outlook.com');
INSERT INTO universidad.estudiante(cod_Estudiante, cod_Carrera, Nombre, Dirección, Correoelectrónico) VALUES
(675, 10008, 'ARNEZ BERBETTY RAQUEL ARELI', 'CALLE VICENTE Nº 661 EDIFICIO VINCENTI', 'lagonzalezoso@gmail.com');
INSERT INTO universidad.estudiante(cod_Estudiante, cod_Carrera, Nombre, Dirección, Correoelectrónico) VALUES
(676, 10008, 'ARNEZ MARQUEZ RICARDO', '', 'alizza.gorena.cordero@gmail.com');
INSERT INTO universidad.estudiante(cod_Estudiante, cod_Carrera, Nombre, Dirección, Correoelectrónico) VALUES
(677, 10008, 'ARNEZ VARGAS ALEJANDRO RUSLAN', '', 'sergorena@gmail.com');
INSERT INTO universidad.estudiante(cod_Estudiante, cod_Carrera, Nombre, Dirección, Correoelectrónico) VALUES
(678, 10008, 'ARPASI CRUZ MAYUMI LYS', 'VENEZUELA # 1070 (ZONA MURURINA)', 'andy.gosalvez@gmail.com');
INSERT INTO universidad.estudiante(cod_Estudiante, cod_Carrera, Nombre, Dirección, Correoelectrónico) VALUES
(679, 10008, 'ARROYO LOPEZ JUAN PABLO', 'C/WALLPARRIMACHI Nº1662 EDIFICIO BARCELO TORRE II-PISO 5 DPT.5H', 'al.gottret@gmail.com');
INSERT INTO universidad.estudiante(cod_Estudiante, cod_Carrera, Nombre, Dirección, Correoelectrónico) VALUES
(680, 10008, 'ARRUETA ANTEQUERA RICARDO ANTONIO', 'CALLE FEDERICO SUAZO EDIF. ALCAZAR TORRE CORDOVA NO. 5F', 'vgoytia@upb.edu');
INSERT INTO universidad.estudiante(cod_Estudiante, cod_Carrera, Nombre, Dirección, Correoelectrónico) VALUES
(681, 10008, 'ARTERO CLAURE PAOLA MICAELA', 'C. 23 DE MARZO Y 2O DE DICIEMBRE', 'leogrecu@gmail.com');
INSERT INTO universidad.estudiante(cod_Estudiante, cod_Carrera, Nombre, Dirección, Correoelectrónico) VALUES
(682, 10008, 'ARZE BAPTISTA NADIA VALERIA', 'PACATA BAJA CALLE ARANIVAR DE MATO 59', 'gustavoga@me.com');
INSERT INTO universidad.estudiante(cod_Estudiante, cod_Carrera, Nombre, Dirección, Correoelectrónico) VALUES
(683, 10008, 'ASPIAZU VOGTSCHMIDT ARETHA LENNY', '', 'alejandrita_95gl@hotmail.com');
INSERT INTO universidad.estudiante(cod_Estudiante, cod_Carrera, Nombre, Dirección, Correoelectrónico) VALUES
(684, 10008, 'ASTURIZAGA GARCIA MIGUEL ANGEL', 'URB. LAREDO # 10 (ZONA  QUINTANILLA)', 'nicolasguardia@hotmail.com');
INSERT INTO universidad.estudiante(cod_Estudiante, cod_Carrera, Nombre, Dirección, Correoelectrónico) VALUES
(685, 10009, 'AUAD PACHECO JOSE', 'MARTIN DE LA ROCHA # 1223 (ZONA CALA CALA)', 'isabelg.a@hotmail.com');
INSERT INTO universidad.estudiante(cod_Estudiante, cod_Carrera, Nombre, Dirección, Correoelectrónico) VALUES
(686, 10009, 'AVILA AGREDA CAROLINA', 'CALLE CAMPERO ED. SEÑOR DE MAYO PISO 3', 'camilarosembluth@gmail.com');
INSERT INTO universidad.estudiante(cod_Estudiante, cod_Carrera, Nombre, Dirección, Correoelectrónico) VALUES
(687, 10009, 'AVILA BARRERO DANIEL', 'C. MENDEZ # 671', NULL);
INSERT INTO universidad.estudiante(cod_Estudiante, cod_Carrera, Nombre, Dirección, Correoelectrónico) VALUES
(688, 10009, 'AVILA MARQUEZ MONIKA', 'URB. SEQUOIA MANZANO BB NO. 9', NULL);
INSERT INTO universidad.estudiante(cod_Estudiante, cod_Carrera, Nombre, Dirección, Correoelectrónico) VALUES
(689, 10009, 'AVILA MERCADO MARCO', 'REDUCTO - TIQUIPAYA', 'jeanp.gulick@gmail.com');
INSERT INTO universidad.estudiante(cod_Estudiante, cod_Carrera, Nombre, Dirección, Correoelectrónico) VALUES
(690, 10009, 'AVILA NAVA GIOVANNI ELMER', 'C. MONTEAGUDO ENTRE AMERICA Y BUENOS AIRES EDIF ACUARELA 5B', 'andyleogumcla@hotmail.com');
INSERT INTO universidad.estudiante(cod_Estudiante, cod_Carrera, Nombre, Dirección, Correoelectrónico) VALUES
(691, 10009, 'AYALA ALEMAN DIEGO RODRIGO', 'AV. ANICETO MEDINA NRO. 156, KM. 3.5 A SACABA', 'krisguty@gmail.com');
INSERT INTO universidad.estudiante(cod_Estudiante, cod_Carrera, Nombre, Dirección, Correoelectrónico) VALUES
(692, 10010, 'AYALA HOPP ARTURO ANDRÉ', 'PASAJE 12 DE JUNIO VILLA MERCEDES CASA N° 100', 'karinemily07@gmail.com');
INSERT INTO universidad.estudiante(cod_Estudiante, cod_Carrera, Nombre, Dirección, Correoelectrónico) VALUES
(693, 10010, 'AYALA TORRES STEPHANIE TATIANA', 'CALLE 5 NO. 978 IRPAVI', 'zephora.gutierrez@gmail.com');
INSERT INTO universidad.estudiante(cod_Estudiante, cod_Carrera, Nombre, Dirección, Correoelectrónico) VALUES
(694, 10010, 'AYALA VILLACORTA ANA MARIA', '', NULL);
INSERT INTO universidad.estudiante(cod_Estudiante, cod_Carrera, Nombre, Dirección, Correoelectrónico) VALUES
(695, 10010, 'AYAVIRI ABASTO SERGIO GUILLERMO', 'AV. SANTA CRUZ # 1466 CASI BUENOS AIRES', 'kgutierrez@upb.edu');
INSERT INTO universidad.estudiante(cod_Estudiante, cod_Carrera, Nombre, Dirección, Correoelectrónico) VALUES
(696, 10010, 'AYAVIRI MALDONADO OLGA FERNANDA', 'C. NUEVA CASTILLA #1728', 'goxadriana@gmail.com');
INSERT INTO universidad.estudiante(cod_Estudiante, cod_Carrera, Nombre, Dirección, Correoelectrónico) VALUES
(697, 10010, 'AYLLON CALDERON CRISTHIAN BRUNO', 'LOS PINOS CALLE 7', 'pgutierrez@upb.edu');
INSERT INTO universidad.estudiante(cod_Estudiante, cod_Carrera, Nombre, Dirección, Correoelectrónico) VALUES
(698, 10010, 'AZUGA BLEICHNER MATEO RAUL', 'PARQUE LINCOLN #520', 'rosendo_agt@icloud.com');
INSERT INTO universidad.estudiante(cod_Estudiante, cod_Carrera, Nombre, Dirección, Correoelectrónico) VALUES
(699, 10010, 'BACARREZA COSTA MAURICIO SILVESTRE', 'CALLE ASPIAZU NO. 1149 ZONA LA MERCED', 'jorge_i_94@hotmail.com');
INSERT INTO universidad.estudiante(cod_Estudiante, cod_Carrera, Nombre, Dirección, Correoelectrónico) VALUES
(700, 10010, 'BADANI ZAMBRANA LOTHAR MARCELO', '25 DE MAYO ESQUINA CALAMA #0482', 'mguzman5@upb.edu');
INSERT INTO universidad.estudiante(cod_Estudiante, cod_Carrera, Nombre, Dirección, Correoelectrónico) VALUES
(NULL, NULL, '', '', NULL);
ROLLBACK;