--
-- Script was generated by Devart dbForge Studio for MySQL, Version 8.0.40.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 7/9/2018 16:28:53
-- Server version: 5.5.5-10.1.34-MariaDB
-- Client version: 4.1
--


SET NAMES 'utf8';

--
-- Inserting data into table universidad.materia
--
INSERT INTO universidad.materia(cod_Materia, Nombre, Fecha_Inicio, Fecha_Final, Horario, Créditos, total_a_pagar) VALUES
(NULL, '', NULL, NULL, '', NULL, NULL),
(NULL, '', NULL, NULL, '', NULL, NULL),
(NULL, '', NULL, NULL, '', NULL, NULL),
(NULL, '', NULL, NULL, '', NULL, NULL),
(NULL, '', NULL, NULL, '', NULL, NULL),
(NULL, '', NULL, NULL, '', NULL, NULL),
(NULL, '', NULL, NULL, '', NULL, NULL),
(NULL, '', NULL, NULL, '', NULL, NULL),
(NULL, '', NULL, NULL, '', NULL, NULL),
(5010, 'FISICA II', '2018-10-11', '2018-11-29', 'B', 4, 4),
(5011, 'FISICA III', '2018-03-25', '2018-05-12', 'C', 4, 4),
(5012, 'GESTION FINANCIERA', '2018-02-03', '2018-03-23', 'D', 4, 4),
(5013, 'INNOVACION Y CREATIVIDAD', '2018-05-14', '2018-06-30', 'E', 4, 4),
(5014, 'INSTRUMENTACION Y AUTOMATIZACION', '2018-09-18', '2018-11-29', 'F', 5, 5),
(5015, 'MATEMATICAS PARA INGENIERIA I', '2018-08-01', '2018-09-16', 'A', 4, 4),
(5016, 'MATEMATICAS PARA INGENIERIA II', '2018-10-11', '2018-11-29', 'B', 4, 4),
(5017, 'MATEMATICAS PARA INGENIERIA III', '2018-03-25', '2018-05-12', 'C', 4, 4),
(5018, 'MECANICA CLASICA', '2018-05-14', '2018-06-30', 'D', 4, 4),
(5019, 'POLITICA EMPRESARIAL', '2018-02-03', '2018-03-23', 'E', 4, 4),
(5020, 'PROBABILIDAD Y ESTADISTICA', '2018-08-01', '2018-09-16', 'F', 4, 4),
(5021, 'PROCESOS DE MANUFACTURA', '2018-05-14', '2018-06-30', 'A', 4, 4),
(5022, 'PROGRAMACION I', '2018-08-01', '2018-09-16', 'B', 4, 4),
(5023, 'PROGRAMACION II', '2018-03-25', '2018-05-12', 'C', 4, 4),
(5024, 'PROGRAMACION III', '2018-09-18', '2018-11-29', 'D', 5, 5),
(5025, 'QUIMICA I', '2018-05-14', '2018-06-30', 'E', 4, 4),
(5026, 'QUIMICA II', '2018-10-11', '2018-11-29', 'F', 4, 4),
(5027, 'SEGURIDAD INDUSTRIAL', '2018-05-14', '2018-06-30', 'A', 4, 4),
(5028, 'TECNICAS DE COMUNICACIÓN ESCRITA', '2018-03-25', '2018-05-12', 'B', 4, 4),
(5029, 'TECNICAS DE VENTAS', '2018-09-18', '2018-11-29', 'C', 5, 5);